### ISSUE TITLE
How to change prime and offset 

### ISSUE THREAD

**Issue by Bluscream** [znerol/py-fnvhash#2]
please allow changing FNV_32_PRIME and FNV1_32_INIT

**Comment by znerol** [comment]
Thanks for the suggestion. What would be the use case for that?

**Comment by Bluscream** [comment]
[This](https://github.com/Bluscream/MWR-Config-Editor/blob/master/CFGParser%2FUtils%2FExtensions.cs#L11), but in python

**Comment by znerol** [comment]
You might try to just call the [fnva](https://github.com/znerol/py-fnvhash/blob/ea6d6993e1082dee2ca3b9aba7a7eb2b7ab6a52a/fnvhash/__init__.py#L38C5-L38C48) function directly:

```
from fnvhash import fnva

fnva(b'foo', 0x319712C3, 0xB3CB2E29, 2**32)
```

**Edit:** Swapped the parameters. If I'm not mistaken, the offset needs to go first and the prime second.
